name: Build and Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build (default: main)"
        required: true
        type: string
        default: main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Repository
        run: |
          git clone --depth 1 --branch ${{ github.event.inputs.branch }} https://${{ secrets.GH_PAT }}@github.com/${{ secrets.BUILD_REPO }} repo
          cd repo
          git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies Python
        working-directory: repo
        run: |
          python -m pip install --upgrade pip
          pip install -r services/requirements.txt
          pip install pyinstaller

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies Node.js
        working-directory: repo
        run: npm install

      - name: Build Python Service
        working-directory: repo
        run: npm run python:build

      - name: Build Electron App
        working-directory: repo
        run: npm run make

      - name: Get Version And Set Tag
        id: set-tag
        working-directory: repo
        shell: bash
        run: |
          echo "Get version from package.json..."
          VERSION=$(node -p "require('./package.json').version")
          echo "Version: $VERSION"

          BRANCH="${{ github.event.inputs.branch }}"
          SAFE_BRANCH=$(echo "$BRANCH" | sed 's|/|-|g')

          if [ "$SAFE_BRANCH" = "main" ]; then
            TAG="v$VERSION"
          else
            TAG="v$VERSION-$SAFE_BRANCH"
          fi
          echo "Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tool-${{ matrix.os }}-${{ steps.set-tag.outputs.tag }}
          path: repo/out/make/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: releases

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          files: releases/**/*
          tag_name: ${{ needs.build.outputs.tag }}
          name: Tool - ${{ needs.build.outputs.tag }}
          draft: false
          prerelease: false
          preserve_order: true
          repository: ${{ secrets.PUBLISH_REPO }}

  cleanup:
    needs: [build, release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Delete All Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: '*'
