name: Build and Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build (default: main)"
        required: true
        type: string
        default: main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-13]
        node: [22, 23]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Repository
        run: |
          git clone --depth 1 --branch ${{ github.event.inputs.branch }} https://${{ secrets.GH_PAT }}@github.com/${{ secrets.TOOL_REPO }} repo
          cd repo
          git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies Python
        working-directory: repo
        run: |
          python -m pip install --upgrade pip
          pip install -r services/requirements.txt
          pip install pyinstaller

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies Node.js
        working-directory: repo
        run: npm install

      - name: Build Python Service
        working-directory: repo
        run: npm run python:build

      - name: Build Electron App
        working-directory: repo
        run: npm run make
